### ISSUE TITLE
Tag input broken?

### ISSUE THREAD

**Issue by Skulmuk** [kaivi/riek#19]
I get the following issue when trying to add values to a RIETags element:

`Uncaught TypeError: _this2.props.value.add is not a function(…)`

If I try to remove a tag, I get the following:

`newSet.delete is not a function`

My `change` event doesn't fire regardless.

**Comment by tirthbodawala** [comment]
@Skulmuk: I had the same problem before, but when I had a look at the code more accurately, 
we need to pass **Set** as value and not simple array.

So try with set.

Example: 
let tags = new Set(["a", "b", "c"]);
<RIETags
    value={tags}
    propName='tags'
    change={data => this.updateTags(data)}
    />

**Comment by Skulmuk** [comment]
Thanks, @tirthbodawala - didn't see that bit of the documentation. All fixed!
