### ISSUE TITLE
RIEInput is not clickable if data is null / empty string

### ISSUE THREAD

**Issue by snario** [kaivi/riek#2]
```js
<RIEInput value={ data } />
```
is not clickable when data is falsey. Ideally this component should be clickable somehow to enter a value

**Comment by Orangetronic** [comment]
You can solve this with CSS or style properties, by adding a minimum width to the empty span that gets rendered for an empty value :)

**Comment by kaivi** [comment]
Yep, that is indeed a styling issue, just use a `style={{ minWidth: '20px' }}` on the component to make it always visible.

**Comment by springuper** [comment]
Could a hint like `click to edit` make more sense?
