### ISSUE TITLE
Integrate react-edit ideas?

### ISSUE THREAD

**Issue by bebraw** [kaivi/riek#26]
Hi,

I did incidentally something similar at [react-edit](https://github.com/reactabular/react-edit). I extracted it from [my table implementation](https://reactabular.js.org/) so that shaped the API somewhat.

I wonder if it would make sense to merge these components somehow. If it was possible to get the `edit` wrapper to riek and port boolean to it (it's a little different there), that would allow me to deprecate react-edit in favor of a more established option.

**Comment by kaivi** [comment]
Both libs do almost the same, I can't see anything that could be merged here...
