### ISSUE TITLE
'RIENumber' doesn't work on firefox

### ISSUE THREAD

**Issue by Linh-Vu** [kaivi/riek#28]
Hi,
i use RIENumber in my app. But it not work on Firefox browser.
http://kaivi.github.io/riek/ your demo doesn't work on Firefox browser

**Comment by tab00** [comment]
I just tried the demo at http://kaivi.github.io/riek/ and found the same problem -the `RIENumber` components don't work in a Firefox browser but is OK in Chrome.

**Comment by tab00** [comment]
Has this repository been abandoned?

What is a good alternative for in-place editing?

**Comment by kaivi** [comment]
Fixed in v1.0.9
