### ISSUE TITLE
Editing state should remain if validation fails even if focus is lost

### ISSUE THREAD

**Issue by tab00** [kaivi/riek#34]
A user may have spent a long time entering new text in an input or text area field. If the user clicks somewhere else, and for some reason (e.g. maximum length exceeded) validation fails, all new text is lost as the field reverts to the non-editing state with old text.

Such a user experience is unacceptable, as a lot of time would have been wasted by the user and he or she would feel angry.

Therefore, if validation fails, the field should remain in editing state so that the user is given a chance to make corrections.

**Comment by tab00** [comment]
It appears that the fork by @springuper fixes the problem: https://github.com/springuper/riek/commit/741c75d808f25d3ef5ecf1483162e24abb6bd677

Though it would be good to have the fix merged into the main repository. We need a new maintainer.

**Comment by springuper** [comment]
feels the same. we're using inline editing heavily, hopefully we could do some contributions.

**Comment by kaivi** [comment]
Added in v1.0.8
