### ISSUE TITLE
Validator required (?)

### ISSUE THREAD

**Issue by jashmenn** [kaivi/riek#41]
Hello! It seems to me that `RIEInput` _requires_ a validation function or else it always fails validation.

Here https://github.com/kaivi/riek/blob/master/src/RIEBase.js#L52 if there is no validator set, the state is set as invalid. `RIEInput` is never given a validator that defaults to true. 

This is a breaking change from earlier versions and I suspect it's a bug because the docs mark `validator` as optional.

**Comment by kaivi** [comment]
Fixed in v1.1.0
