### ISSUE TITLE
Empty value causes edit field to disappear

### ISSUE THREAD

**Issue by purplejacket** [kaivi/riek#54]
If there is no data in the input field, the element vanishes and the user cannot put in a new value.  E.g., in the demo, click the "Example text value" value, erase it, press enter, and you're hosed.

**Comment by kluzny** [comment]
You can address with with a min-width or an after selector see https://github.com/kaivi/riek/issues/2

**Comment by SimonChris** [comment]
Or just give it a default value:

`<RIEInput` value={ data || 'Enter text here' } />

**Comment by purplejacket** [comment]
Ok, I saw some good solutions proposed in #2 

But now I find another problem:  The same issue exists with the RIETextArea, but the style fixes don't work.  E.g.


        <RIETextArea
          value={this.state.textarea}
          change={this.virtualServerCallback}
          propName="textarea"
          className={this.state.highlight ? "editable" : ""}
          classLoading="loading"
          classInvalid="invalid"
          isDisabled={this.state.isDisabled} />

That's from the demo, but with the validate removed.

Additionally, I've added this styling, as mentioned in #2:

    .editable:empty:after {
      content: 'click-to-edit';
    }

The styling works on the RIEInput that's in the demo, but doesn't work on the RIETextArea above.

**Comment by purplejacket** [comment]
Ok, here is a solution that handles both `RIEInput` and `RIETextArea`:

    .editable:empty:after, .editable span:first-child:empty:after {
        content: 'Click to edit.';
        font-style: italic;
    }

The addition of the `span` into the style handles the `textarea` component, as RIEK inserts an extra nested `span` for the `textarea`.  I might do a pull request for this as it's probably an issue that new users will encounter and waste time on.
